# Generated by Django 5.1.7 on 2025-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Books', 'Books'), ('Toys', 'Toys'), ('Home', 'Home'), ('Other', 'Other')], default='Other', max_length=32),
        ),
    ]
