# Generated by Django 5.2 on 2025-04-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listening'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listening',
            new_name='Listing',
        ),
    ]
